// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AgentCipher",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "AgentCipher",
            targets: ["AppModule"],
            bundleIdentifier: "com.ved.AgentCipher",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .map),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/airbnb/lottie-ios.git", "4.0.0"..<"5.0.0"),
        .package(url: "https://github.com/ivanvorobei/SPConfetti", "1.0.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Lottie", package: "lottie-ios"),
                .product(name: "SPConfetti", package: "spconfetti")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)